// shows/_template/config.ts
//
// Per-show configuration. Every new show generated by /create-show
// produces a file just like this, customized for that show.

import type { ShowConfig } from "../../src/show";

export const config: ShowConfig = {
  // ---------------------------------------------------------------------------
  // Identity
  // ---------------------------------------------------------------------------
  showKey: "_template",                       // short slug used in URLs and config keys
  showTitle: "Show Title",                    // human-readable show name
  hostName: "Host Name",                      // name spoken in the intro/outro
  publisher: "The Penny Tribune",             // typically the same across shows
  copyrightHolder: "The Penny Tribune",       // typically the same across shows
  podcastGenre: "News",                       // News / Society & Culture / Technology / etc.

  // ---------------------------------------------------------------------------
  // Editorial
  // ---------------------------------------------------------------------------
  // The episode-date opening sentence (substitute [HOST NAME] and [CURRENT DATE]
  // placeholders at runtime).
  openingTemplate:
    'Good morning, today is [CURRENT DATE]. I am [HOST NAME], and this is [SHOW TITLE] from [PUBLISHER].',
  closingTemplate:
    'I am [HOST NAME]. Thank you for listening to [SHOW TITLE]. We will see you next time.',

  // ---------------------------------------------------------------------------
  // Length targets
  // ---------------------------------------------------------------------------
  minScriptWords: 3300,
  targetScriptWordsMin: 3300,
  targetScriptWordsMax: 3700,
  maxScriptWords: 3900,
  wordsPerMinute: 145,

  // ---------------------------------------------------------------------------
  // TTS chunking
  // ---------------------------------------------------------------------------
  maxTtsCharsPerChunk: 2500,

  // ---------------------------------------------------------------------------
  // Sound sequence
  //
  // Each show's audio assets live in the repo at:
  //
  //   assets/sounds/<showKey>/
  //
  // (Committed to git so the whole team gets them on `git pull`.)
  //
  // The pipeline assembles each episode like this:
  //
  //   intro[0], intro[1], …, intro[N]
  //   chunk-001, sectionSting, chunk-002, sectionSting, …, chunk-NNN
  //   outro[0], outro[1], …, outro[M]
  //
  // Standardized filenames every show uses by default:
  //
  //   intro.wav            intro music bed
  //   intro-sting.wav      "now the news begins" transition
  //   section-sting.wav    transition between sections
  //   outro.wav            outro / thank-you bed
  //
  // To add additional intro/outro elements (signature foley, voiced
  // greeting, etc.), list the extra filenames in order — they're resolved
  // relative to Sounds/<showKey>/.
  // ---------------------------------------------------------------------------
  sounds: {
    intro: ["intro.wav", "intro-sting.wav"],
    sectionSting: "section-sting.wav",
    outro: ["outro.wav"],
  },

  // ---------------------------------------------------------------------------
  // Topic flow — the editorial backbone of the show.
  //
  // Each entry becomes a section in the script with a [TEN-SECOND SECTION SPACER]
  // before it and a chapter marker on the rendered MP3. Keep section names short
  // (Title Case) so they read well as spoken transitions ("Now, the Power Map.").
  // ---------------------------------------------------------------------------
  topicFlow: [
    "Positive Opening",
    "Top Story",
    "Headlines",
    "Closing",
  ],

  // ---------------------------------------------------------------------------
  // WordPress / Apollo plugin
  // ---------------------------------------------------------------------------
  wpParentPodcastId: 0,                      // serve_podcast post ID for this show
  wpPodcastShowTerm: "Show Title",           // matches a serve_podcast_category term

  // ---------------------------------------------------------------------------
  // Google Drive — the destination folder for this show's archive
  // ---------------------------------------------------------------------------
  googleDriveFolderId: "",
};
